import { Injectable, Logger } from '@nestjs/common';
import { Octokit } from '@octokit/rest';

// GitHub에 push할 파일 1개의 경로 + 내용
export interface GitHubFile {
  path: string;
  content: string;
}

// GithubService
// GitHub PAT를 사용해 repo를 생성하고 파일 목록을 최초 커밋으로 push한다.
// GitHub REST API(Octokit)만 사용하므로 git binary나 임시 디렉토리가 필요 없다.
//
// push 흐름 (신규 빈 repo 기준):
//   1. 인증된 유저 정보 조회 (owner 확인)
//   2. repo 생성 (auto_init: false — 빈 repo)
//   3. 각 파일의 blob을 병렬 생성 (SHA 리스트)
//   4. 전체 파일을 담은 tree 생성 (base tree 없음 — 첫 커밋)
//   5. tree를 가리키는 commit 생성 (parent 없음 — 첫 커밋)
//   6. main 브랜치 ref 생성 → commit SHA를 가리킴
@Injectable()
export class GithubService {
  private readonly logger = new Logger(GithubService.name);

  // 생성된 repo URL을 반환한다. Project.githubRepoUrl에 저장된다.
  async pushFiles(
    token: string,
    repoName: string,
    isPrivate: boolean,
    files: GitHubFile[],
  ): Promise<string> {
    const octokit = new Octokit({ auth: token });

    // 1. 인증된 GitHub 유저 조회 — repo 소유자(owner) 확보
    const { data: user } = await octokit.rest.users.getAuthenticated();
    const owner = user.login;

    this.logger.log(`GitHub push start — owner=${owner} repo=${repoName} files=${files.length}`);

    // 2. repo 생성. auto_init: false → 빈 repo (README 없음). 첫 커밋을 수동으로 생성
    await octokit.rest.repos.createForAuthenticatedUser({
      name: repoName,
      private: isPrivate,
      auto_init: false,
    });

    // 3. 각 파일의 내용을 base64 인코딩한 blob으로 변환 (병렬)
    // blob은 git의 파일 데이터 단위 — SHA로 참조됨
    const blobs = await Promise.all(
      files.map(async (file) => {
        const { data } = await octokit.rest.git.createBlob({
          owner,
          repo: repoName,
          content: Buffer.from(file.content).toString('base64'),
          encoding: 'base64',
        });
        return { path: file.path, sha: data.sha };
      }),
    );

    // 4. blob SHA 목록으로 tree 생성. base_tree를 생략하면 루트 tree로 취급 (첫 커밋)
    const { data: tree } = await octokit.rest.git.createTree({
      owner,
      repo: repoName,
      tree: blobs.map((b) => ({
        path: b.path,
        mode: '100644', // 일반 파일
        type: 'blob',
        sha: b.sha,
      })),
    });

    // 5. tree를 가리키는 commit 생성. parents 빈 배열 → 첫 커밋 (부모 없음)
    const { data: commit } = await octokit.rest.git.createCommit({
      owner,
      repo: repoName,
      message: 'Initial commit — generated by MVP Builder',
      tree: tree.sha,
      parents: [],
    });

    // 6. main 브랜치 ref를 commit SHA로 생성 (refs/heads/main)
    await octokit.rest.git.createRef({
      owner,
      repo: repoName,
      ref: 'refs/heads/main',
      sha: commit.sha,
    });

    const repoUrl = `https://github.com/${owner}/${repoName}`;
    this.logger.log(`GitHub push complete — ${repoUrl}`);
    return repoUrl;
  }
}
